language: python

cache: pip

env:
  global:
    - PYYAML_TEST_GROUP=all

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8-dev
      env: TOXENV=py38
    - python: 3.7
      arch: arm64
      env: TOXENV=py37
    - python: 3.8
      arch: arm64
      env: TOXENV=py38
    - python: 3.8-dev
      arch: arm64
      env: TOXENV=py38
    - python: pypy
      env: TOXENV=pypy

# build libyaml
before_script:
  - bash ./packaging/build/libyaml.sh

install: pip install cython tox

script: tox
