# dist: xenial

cache: pip

env:
  global:
    - PYYAML_TEST_GROUP=all

matrix:
  include:
    - language: python
      python: 2.7
      env: TOXENV=py27 JOBTYPE=test
    - language: python
      python: 3.5
      env: TOXENV=py35 JOBTYPE=test
    - language: python
      python: 3.6
      env: TOXENV=py36 JOBTYPE=test
    - language: python
      python: 3.7
      env: TOXENV=py37 JOBTYPE=test
    - language: python
      python: 3.8
      env: TOXENV=py38 JOBTYPE=test
    - language: python
      python: 3.8-dev
      env: TOXENV=py38 JOBTYPE=test
    - language: python
      python: 3.7
      arch: arm64
      env: TOXENV=py37 JOBTYPE=test
    - language: python
      python: 3.8
      arch: arm64
      env: TOXENV=py38 JOBTYPE=test
    - language: python
      python: 3.8-dev
      arch: arm64
      env: TOXENV=py38 JOBTYPE=test
    - language: python
      python: pypy
      env: TOXENV=pypy JOBTYPE=test
    - name: manylinux2014-x86-64
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64:latest
           PLAT=manylinux2014_x86_64
           JOBTYPE=wheels-manylinux
    - name: purepython-3-wheels
      language: python
      python: 2.7
      env: JOBTYPE=wheels-pure-py
    - name: purepython2-wheels
      language: python
      python: 3.7
      env: JOBTYPE=wheels-pure-py

before_script:
  - if [[ "$JOBTYPE" == "test" ]]; then ./packaging/build/libyaml.sh; fi

install:
  - if [[ "$JOBTYPE" == "test" ]]; then pip install cython tox; fi
  - if [[ "$JOBTYPE" == "wheels-pure-py" ]]; then
      pip install -u setuptools wheel;
    fi

script:
  - if [[ "$JOBTYPE" == "test" ]]; then tox; fi
  - if [[ "$JOBTYPE" == "wheels-manylinux" ]]; then
      docker container run --rm -e PLAT="$PLAT" -v "$(pwd)":/io --workdir '/io' $DOCKER_IMAGE /io/packaging/build/manylinux.sh;
    fi
  - if [[ "$JOBTYPE" == "wheels-pure-py" ]]; then python setup.py bdist_wheel; fi
