---

name: Build wheels
on: push
jobs:
  manylinux_wheels:
    name: Python ${{ matrix.python_tag }} ${{ matrix.platform }} wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v2
      - name: Install Docker
        run: sudo apt-get install -y --no-install-recommends docker
      - name: Pull Docker image
        run: |
          DOCKER_IMAGE="quay.io/pypa/${{ matrix.platform }}"
          echo "::set-env name=DOCKER_IMAGE::$DOCKER_IMAGE"
          docker image pull "$DOCKER_IMAGE"
      - name: Build manylinux wheels
        env:
          PYTHON_TAGS: 'cp35-cp35m cp36-cp36m cp37-cp37m cp38-cp38'
        run: |
          docker container run \
            --rm \
            -e PLAT=${{ matrix.platform }} \
            -e PYTHON_TAGS="$PYTHON_TAGS" \
            -v "$(pwd)":/io \
            --workdir '/io' \
            "$DOCKER_IMAGE" \
            /io/packaging/build/manylinux.sh
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  macosx_wheels:
    name: Python ${{ matrix.python_version }} MacOS wheels
    # Note: the container MacOS version may differ from the SDK
    # used to build Python there.  It is the latter that determines
    # the wheel's platform tag.
    # https://github.com/actions/virtual-environments/issues/696
    #
    # See also:
    # https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
    # for environment description.
    runs-on: macos-latest
    strategy:
      matrix:
        python_version: [3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Upgrade build tools
        # Brew install may issue a warning if already installed
        # but should exit 0 regardless
        run: |
          brew update -q
          brew upgrade
          brew install automake
      - name: Build LibYAML
        run: bash ./packaging/build/libyaml.sh
      - name: Build MacOS wheels
        run: bash ./packaging/build/macos.sh
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  purepy_wheels:
    name: Pure-Python wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build pure-Python wheels
        run: |
          python -m pip install -U wheel setuptools
          python setup.py bdist_wheel
          ls -1 dist
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
